#!/bin/bash
#
################################################
## The script to call to open the plugin. To
## open the plugin with a particular file, pass
## the file name as an argument.
##
################################################
FIJIPATH=/nrims/common/local/Fiji.app
cd $FIJIPATH
./ImageJ-linux64 -eval "run('Open MIMS Image', '-single_instance $@')" >&  $FIJIPATH/logs/logfile_$(whoami)_$(hostname)_$$.txt
